# Generated by Django 4.0.4 on 2022-08-20 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employe',
            old_name='phone',
            new_name='phonenumber',
        ),
    ]
